### ISSUE TITLE
请问有webSocket-Server的DEMO吗？

### ISSUE THREAD

**Issue by BalancedTernary** [IronsDu/brynet#105]

**Comment by BalancedTernary** [comment]
我运行这个例子后，在前端使用“let ws=new WebSocket("ws://localhost:8182");”语句无法成功建立websocket连接，请问是还需要什么操作吗?

**Comment by IronsDu** [comment]
@BalancedTernary 发送http的时候，要在http的header里设置下。

**Comment by BalancedTernary** [comment]
问题已解决，非常感谢。

**Comment by IronsDu** [comment]
我先关闭issue，若还有问题欢迎提交issue。
