### ISSUE TITLE
wss支持cdn转发吗

### ISSUE THREAD

**Issue by inaryart** [IronsDu/brynet#110]
我在使用的另一个库的wss客户端 一但开启cdn便无法访问，想知道这个库是否支持cdn

**Comment by IronsDu** [comment]
你好，这个高级功能需要自己编写，库没有提供。

**Comment by inaryart** [comment]
> 你好，这个高级功能需要自己编写，库没有提供。

以你这个库的wss实现为例，有什么建议吗，我需要做哪些步骤才能实现这个功能

**Comment by IronsDu** [comment]
或许你应该实现一个proxy。我也没有具体做过CDN。CDN应该是发送一个重定向给客户端。我不知道wsss跟CDN有什么关系呢。

**Comment by inaryart** [comment]
是的 原理上 cdn与wss 没什么联系 ，但是wss客户端需要支持cdn那么应该需要做些特定的处理 这是我的理解。。。

**Comment by IronsDu** [comment]
这个可以先了解一下相关通信协议上的支持哈。然后就可以利用brynet来发送相关格式协议了。
