### ISSUE TITLE
CodeQL没有正确配置

### ISSUE THREAD

**Issue by xth** [IronsDu/brynet#114]
提交了代码，却被告之“No code found during the build. ”

**Comment by IronsDu** [comment]
是的啊。我还没搞定怎么分析。貌似对header only不太友好。

**Comment by xth** [comment]
会不会是因为不识别.hpp文件？

**Comment by IronsDu** [comment]
我感觉跟编译单元有关系。毕竟一个.h/hpp不是一个编译单元，没法分析。

**Comment by IronsDu** [comment]
已经解决了。是因为默认CMake没有编译example。
