### ISSUE TITLE
我在ue中尝试使用这个库，但是貌似它连上后就没什么反应了

### ISSUE THREAD

**Issue by ActivePeter** [IronsDu/brynet#116]
![image](https://user-images.githubusercontent.com/8100696/151856148-8585464d-62a8-4dd4-b398-952cb0c7c4fe.png)
我把他这个tick放在ue的一个task中
brynet是作为客户端连到我的服务端上
连上之后它也触发了回调，
但是我调用它的send貌似就没反应，
后面断开，调用postShutdown也没有反应

**Comment by IronsDu** [comment]
可以抓包看看。或者调用send时加一个回调参数，看看发送没。
