### ISSUE TITLE
some file miss

### ISSUE THREAD

**Issue by gergul** [IronsDu/brynet#13]
brynet\utils\coroutine.c(216): fatal error C1083: 无法打开包括文件: “brynet/utils/stack.h”: No such file or directory

**Comment by IronsDu** [comment]
@gergul 你要用这个协程么？

**Comment by IronsDu** [comment]
@gergul https://github.com/IronsDu/brynet/tree/1d44aaa688b907aeb839bafb450d9903c8bbe75f/common 浏览下这里，从这里下载所需要的文件吧。
