### ISSUE TITLE
例子中的广播报文服务端收不到，请问如何设置IP地址？

### ISSUE THREAD

**Issue by luoyouchun** [IronsDu/brynet#16]
网络状态：
IP：192.168.0.17
掩码：192.168.252.0
网关192.168.0.1

计算后的广播地址：192.168.3.255
命令行调用如下：BroadCaseServer.exe 9999
BroadCaseClient.exe 192.168.3.255 9999 100 100
在同一台计算机上，报文可以发送出去，但服务端程序没有收到。

BroadCaseClient.exe 192.168.0.17 9999 100 100 可以收到回应。

**Comment by IronsDu** [comment]
抱歉，这个广播不是IP层的广播。而是广播给链接到此程序的所有TCP客户端的意思。
`BroadCaseClient.exe 192.168.0.17 9999 100 100 可以收到回应。`  嗯，像这用法才行。
