### ISSUE TITLE
brynet.sln没有提交吧。

### ISSUE THREAD

**Issue by supermario1990** [IronsDu/brynet#3]

**Comment by IronsDu** [comment]
现在换成cmake了。你新建一个目录，譬如build。然后进入build目录执行 cmake ..。即可生成brynet.sln。 不过因为我最近使用了std::any，所以需要VS2017（或者GCC7)，而之前VS 2013就行。

**Comment by supermario1990** [comment]
嗯嗯，谢了。我用vs2017来编译试试
