### ISSUE TITLE
server向已关闭的socket发送数据时的behavior

### ISSUE THREAD

**Issue by wuyuanyi135** [IronsDu/brynet#39]
请问当客户端关闭session时，服务端如果对该session继续写入数据，会有什么样的表现？是会抛出异常吗

**Comment by IronsDu** [comment]
你好.

1. 目前的'send' 调用不会有异常
2. 如果已经关闭,那么''send'的完成回调永远不会被调用.
你期望：
a: 当底层已经知道session网络断开了，那么'send'函数产生异常？
b: 给'send'再提供额外的回调，当底层知道session断开，那么触发回调函数.

ps,目前session有一个统一的断开回调:'setDisConnectCallback'，当session网络断开会触发此回调.

**Comment by wuyuanyi135** [comment]
@IronsDu 多谢！
例如我有一个程序，收到ping后过10秒开始每1秒向发送机回发pong消息。 根据我的测试，由于没有异常和侦测机制，后面的连续发送pong没有停止的依据。我可以用 链接/断开回调来维护一个已连接客户端的列表，在发送前检测该session是否还存在。但是我想请问发送失败的机制是否有更加explicit的处理方法？

另外，请问session的shared_ptr在连接断开时是否会被释放？如果我需要保存实例是否应该保存其weakptr?我是否能用这个weakptr的有效与否来直接判断session的有效性？

多谢！

**Comment by IronsDu** [comment]
1. 确实因为没有发送时的主动侦测机制，所以必须用额外的会话列表来辅助检测。
2. 这个会话列表最好采用map并且无论啥时候key不会重复(比如用递增id来做session id，且考虑线程安全)。
网络断开后，底层的TcpConnection::Ptr会被从底层的map里移除，所以你说的会话列表里用weak ptr是正确的且推荐的方式!
 (如果不直接用弱指针，那你需要设计单独的结构作为会话列表里的ValueType，其中会储存一个bool链接状态)
 (另外，如果不用弱指针，那么也请在收到断开回调后，将那个指针显式设置为null，不然它的析构函数一直不会调用 !)

3.如果要send支持异常，或许需要底层拦截下断开回调(做类似上面的处理)(然后再断开回调给用户)，然后就能让用户在下一次发送立即得到异常。(貌似确实方便)
现在主要问题是:我在想你这个需求是不是一个广泛(且方便用户)的需求？  

你提的这几点很好，感谢。

**Comment by wuyuanyi135** [comment]
谢谢回复
关于第二点， 你是说在disconnect的回调中必须要把session的共享指针显式的reset吗？ 这点我有疑问：在disconnect回调就算不释放指针，在离开函数定义域后应该会自动将自动将引用计数减少。那么不管在disconnect中是否显式释放session指针，应该不会影响该变量的释放才对。请问是否能解释一下这一点？
关于 3. 我之前用的是boost::asio来实现跨平台tcp。在他们的实现中 如果我没有记错，是没有disconnect的回调的。他们通过向event loop添加accept, send 和 receive任务，并且在send 和receive回调中传入出现exception的error code. 也就是说，在eventloop执行send和receive任务出错时，使用者有义务判断是否对方已经断开并且执行清理操作。
我个人不是很了解底层的处理方式，请问brynet的断开检测是利用什么机制的呢？是heartbeat，或者是依赖于对方发来的断开信息？

**Comment by IronsDu** [comment]
1. 如果你的业务层持有`TcpConnection::Ptr` shared_ptr指针，那么在收到断开回调时，需要将业务层的那个指针设置为nullptr. 否则引用计数一直不为0就不会析构TcpConnection咯。
2.嗯，其实就是一个封装，这样用户不必去做那些检测。底层的机制一方面是heartbeat，另外一方面就是recv/send系统调用或者epoll/iocp拿到的错误来判断。

**Comment by wuyuanyi135** [comment]
ok 多谢！ 了解了
