### ISSUE TITLE
Does this work with Android/iOS?

### ISSUE THREAD

**Issue by soknifedev** [IronsDu/brynet#40]
Hi, I'm planning to build a cross-platform program which must work in windows, linux, macOS, **android and iOS**.

Does brynet works with all of these platforms? (of course, in android, for example, using the NDK + JNI).

If it isn't, which libraries are using brynet that are incompatible? 

Regards,
Knife.

**Comment by IronsDu** [comment]
Hi, This answer is whether we can use `epoll` in Android and `kqueue` in IOS.
I never use Android and IOS, Sorry I don't test for you. 
Can you test some API of `epoll` and 'kqueue' ?

**Comment by IronsDu** [comment]
@knife-dev Hi, Can you build brynet with Android/iOS?

**Comment by halx99** [comment]
@knife-dev Hi, this lib support both win32,android,ios,macos,linux: https://github.com/simdsoft/yasio, you can try it

**Comment by qht1003077897** [comment]
I have tested that it can be supported on Android platform

**Comment by qht1003077897** [comment]
Thank you, author.@IronsDu

**Comment by IronsDu** [comment]
@soknifedev I want close this issue. If you have any question, please reopen it.
