### ISSUE TITLE
mac下cmake修改

### ISSUE THREAD

**Issue by NickYang1988** [IronsDu/brynet#41]
不想提交PR了，mac下cmakelist这里修改下，这样编译出来的libbrynet.dylib的install name为
@rpath/libbrynet.dylib (compatibility version 0.0.0, current version 0.0.0)
相当于gcc下的-Wl -rpath=xxx

```txt
if(APPLE)
  set(CMAKE_MACOSX_RPATH 0)
endif()
```
修改为
```cmake
if(APPLE)
  set(CMAKE_MACOSX_RPATH 1)
endif()
```

**Comment by IronsDu** [comment]
谢谢，已修复。https://github.com/IronsDu/brynet/commit/6c21c1e8018d223fd6f7e76a758190111df57db8
