### ISSUE TITLE
请问它支持自动重连吗

### ISSUE THREAD

**Issue by nqf** [IronsDu/brynet#45]
希望可以设置一个参数， 当网络连接断开时候自动重连

**Comment by IronsDu** [comment]
#18 可以看下这里的讨论哈。
因为断线重连不应该是网络库的功能。（毕竟从现实来讲，重连之后和之前，有一些业务事情要做）
这是一个框架或者上层库的功能（让玩家不管理网络，作为一个黑盒），这些库的内部可以帮助用户自动重连，这是没问题的。
