### ISSUE TITLE
服务端断开连接后，过了大概20s才收到disconnect回调

### ISSUE THREAD

**Issue by qht1003077897** [IronsDu/brynet#46]
我是拔掉服务端网线的，然后过了很久才收到disconnect的回调，这个库能立即受到socket断开的回调吗？ @IronsDu

**Comment by IronsDu** [comment]
@qht1003077897 拔掉网线这种没法处理，因为没法发送FIN。所以应用层都需要添加心跳检测（当然brynet底层也提供了心跳检测，另外TCP底层也可以打开keepalive机制). （但都做不到立即触发断开）

**Comment by qht1003077897** [comment]
好的 那么再请问下brynet内部的心跳是怎么实现的呢  通过发送数据包吗？ 如果是的话那么发送的内容是什么呢，服务端怎么知道这是心跳包呢

**Comment by IronsDu** [comment]
@qht1003077897 
抱歉，我可能之前说的有歧义。
brynet内部只做了心跳检测，但并没有做心跳（发送）。

也就是说bryent内部做的仅仅是检测一定时间内有没有接收到对方消息。（但心跳检测功能本身并不做任何收发操作）

**Comment by qht1003077897** [comment]
好的 明白了 感谢
