### ISSUE TITLE
hope the examples is simple

### ISSUE THREAD

**Issue by nblog** [IronsDu/brynet#48]
希望可以examples里面加一点简单点的例子, 例如普通的Client和Server, 原谅我例子里面一个都没看懂...  我只是个小白  希望有一点简单的client server例子即可  感谢 👍

**Comment by IronsDu** [comment]
很抱歉，确实没有太简单的例子了，不妨看看文档？
https://github.com/IronsDu/brynet/blob/master/docs/main.zh-cn.md

另外，我觉得你是否对C++11不太熟悉？ 可以看这里学习下：https://docs.microsoft.com/zh-cn/cpp/cpp/welcome-back-to-cpp-modern-cpp?view=vs-2019

**Comment by nblog** [comment]
老哥 我想再问下 如何主动recv?  我看里面大部分都是setDataCallback里面回调  如果我想主动去recv该如何实现?
期待你的回答  :)

**Comment by IronsDu** [comment]
这个库不需要用户去控制recv，底层会自动（主动）发起Recv。所以没办法像你说的“主动去recv”。

asio需要用户投递recv，我想那就是你想问的效果吧？
