### ISSUE TITLE
How to get a list of opened sessions ?

### ISSUE THREAD

**Issue by jagernicolas** [IronsDu/brynet#58]
Hi,
I'd like to send messages from the server to every client connected (using websocket). I don't see how to do that. I was expecting to find a list with all the sessions opened.

there is a way to send messages to each client from the server (using websocket) ?

thx

**Comment by IronsDu** [comment]
@jagernicolas 
Hi, see here:
https://github.com/IronsDu/brynet/blob/4879414c1ecd5c3159f9b16c7d113057fdbeb666/examples/HttpServer.cpp#L40-L53

When session enter, We can push `HttpSession::Ptr` into session list(need mutex).

And, we can use `HttpSessionHandlers::setClosedCallback` for remove session from session list, like this:
https://github.com/IronsDu/brynet/blob/4879414c1ecd5c3159f9b16c7d113057fdbeb666/examples/HttpServer.cpp#L69-L71

**Comment by IronsDu** [comment]
also add some code in this:
https://github.com/IronsDu/brynet/blob/4879414c1ecd5c3159f9b16c7d113057fdbeb666/examples/BenchWebsocket.cpp#L56-L82

**Comment by jagernicolas** [comment]
Hi @IronsDu ,
I was exactly doing that... however here my mistake,
`std::list<HttpSession::Ptr&> list;`
instead of
`std::list<HttpSession::Ptr> list;`

```
auto wsEnterCallback = [&list](const HttpSession::Ptr& httpSession, 
         WebSocketFormat::WebSocketFrameType opcode, 
         const std::string& payload) { 
             std::cout << "frame enter of type:" << int(opcode) << std::endl; 
             std::cout << "payload is:" << payload << std::endl; 
             // echo frame 

             liste.push_back(session); // TODO: add mutex

             auto frame = std::make_shared<std::string>(); 
             WebSocketFormat::wsFrameBuild(payload.c_str(), 
                 payload.size(), 
                 *frame, 
                 WebSocketFormat::WebSocketFrameType::TEXT_FRAME, 
                 true, 
                 false); 
             httpSession->send(frame); 
```
I will make a short example, would you me to share it with you ? I could make a PR when it's done (today or tomorrow)

**Comment by jagernicolas** [comment]
nevermind, I just saw that your example `BroadCastServer.cpp` show that.

thx @IronsDu for your quick support!

**Comment by IronsDu** [comment]
Thank you. You can make a PR for this example.
