### ISSUE TITLE
请问如何获取HTTP的method和请求带过来的参数？没有看到相关接口？谢谢

### ISSUE THREAD

**Issue by lizengwu** [IronsDu/brynet#61]

**Comment by IronsDu** [comment]
在 `setHttpCallback` 函数设置的HTTP消息处理回调里有一个HTTPParser参数。
比如：https://github.com/IronsDu/brynet/blob/master/examples/HttpServer.cpp#L30 。

我们可以使用 HTTPParser 的 [`getQuery`](https://github.com/IronsDu/brynet/blob/master/include/brynet/net/http/HttpParser.hpp#L64)获取整个query （当然这是一个字符串，需要自己处理其中k=v&k=v的形式）。
如果是要获取body参数则通过 [`getBody`](https://github.com/IronsDu/brynet/blob/master/include/brynet/net/http/HttpParser.hpp#L106)。

另外，你需要知道当前请求的method？也就是说是POST还是GET？好像还真没法获得。需要加代码：将访问 HTTPParser里的http_parser成员的method。

**Comment by lizengwu** [comment]
> 在 `setHttpCallback` 函数设置的HTTP消息处理回调里有一个HTTPParser参数。
> 比如：https://github.com/IronsDu/brynet/blob/master/examples/HttpServer.cpp#L30 。
> 
> 我们可以使用 HTTPParser 的 [`getQuery`](https://github.com/IronsDu/brynet/blob/master/include/brynet/net/http/HttpParser.hpp#L64)获取整个query （当然这是一个字符串，需要自己处理其中k=v&k=v的形式）。
> 如果是要获取body参数则通过 [`getBody`](https://github.com/IronsDu/brynet/blob/master/include/brynet/net/http/HttpParser.hpp#L106)。
> 
> 另外，你需要知道当前请求的method？也就是说是POST还是GET？好像还真没法获得。需要加代码：将访问 HTTPParser里的http_parser成员的method。

写了获取http_parser成员变量method的函数，但是所有的值都是0，是不是底层没有解析method啊？

**Comment by IronsDu** [comment]
我晚上试试。
刚才看了下代码，是不是在 https://github.com/IronsDu/brynet/blob/master/include/brynet/net/http/HttpParser.hpp#L147 给重置了。 你看下这个回调里的取出来的method是否正确呢。如果是的话，可能需要在回调里把method拿出来然后放到HTTPParser对象里就行了。

**Comment by lizengwu** [comment]
我也正在看这段代码，多谢大佬，麻烦您晚上也试试，不胜感激！

**Comment by IronsDu** [comment]
拉取最新master代码试试呢。

commit变更可看：
https://github.com/IronsDu/brynet/commit/d121773de90570daece764403647892de09edd63

**Comment by lizengwu** [comment]
最新的master分支我这边编译有问题，可能是我环境问题，我借助之前的代码在tryParse后，init前保存了Method，可以正确获取Method了，谢谢

**Comment by IronsDu** [comment]
编译报错是啥呢。按道理最小C++11支持的编译器都行。
嗯，你的方式跟我提交的commit一致。

**Comment by lizengwu** [comment]
抱歉，master没问题的，我刚在Linux环境下操作的，手误，删了一个头文件包含

**Comment by lizengwu** [comment]
楼主，vcpkg需要更新了啊，差了两个版本了，x86和x64

**Comment by IronsDu** [comment]
@lizengwu 好的，我空了弄弄。 目前你可以使用 `vcpkg install brynet --head ` 来直接安装最新版。

**Comment by IronsDu** [comment]
可以关闭了issue，若还有问题再重新打开。
