### ISSUE TITLE
HttpClient无法执行

### ISSUE THREAD

**Issue by lizengwu** [IronsDu/brynet#63]
httpserver是可以的，我用postman发包能收到，但是httpclient执行失败，我只修改了Host（改成我目标主机的IP：port），WithAddr修改为我运行httpclient主机的IP，端口依然80，报错 connect failed，请问这个需要改其他地方吗？谢谢

**Comment by lizengwu** [comment]
抱歉，看了代码后发现是自己理解错误。

**Comment by lizengwu** [comment]
客户端解析的body为什么是2组hello world？看代码逻辑应该是一组吧？

connect success
HTTP/1.1 200 OK
Content-Length: 11

<html>hello world </html>
<html>hello world </html>

**Comment by IronsDu** [comment]
@lizengwu 我刚测试了下，我启动httpserver，然后将HttpClient.cpp里的ip改成127.0.0.1，测试结果正确啊。请问你是如何测试的呢？

**Comment by IronsDu** [comment]
HttpClient只建立一个链接到server么？

**Comment by IronsDu** [comment]
我确实不管怎么测试（一个链接）都只会打印一次。

**Comment by lizengwu** [comment]
我再看看，谢谢



---原始邮件---
发件人: "IronsDu"<notifications@github.com&gt;
发送时间: 2020年8月12日(周三) 晚上7:18
收件人: "IronsDu/brynet"<brynet@noreply.github.com&gt;;
抄送: "lizengwu"<786436671@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题: Re: [IronsDu/brynet] HttpClient无法执行 (#63)




 
我确实不管怎么测试（一个链接）都只会打印一次。

**Comment by lizengwu** [comment]
我又下载了一份代码，merge对比了没有任何区别，但是新代码打印就是一份body，无奈了，我先关了，后续有新的情况我再开吧，多谢楼主

**Comment by IronsDu** [comment]
好的，谢谢反应。有问题随时提供。

**Comment by lizengwu** [comment]
大牛，咨询个问题啊，
我看你用了很多次enum class， 我这次也用了，在头文件定义了一个
enum class Service_Type
{
	USER_USAGE,
	BUCKET_STATS
};



但是在cpp文件中使用Service_Type：：USER_USAGE调用的时候，却报错error: ‘Service_Type’ is not a class or namespace，头文件在cpp文件已经包含了，以前都是在同一个文件中使用，这词跨文件，却报错，希望能得到您的回复啊，先谢过




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IronsDu/brynet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 上午10:04
收件人:&nbsp;"IronsDu/brynet"<brynet@noreply.github.com&gt;;
抄送:&nbsp;"786436671"<786436671@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [IronsDu/brynet] HttpClient无法执行 (#63)





 
好的，谢谢反应。有问题随时提供。

**Comment by lizengwu** [comment]
已解决，打扰了，感谢感谢




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "IronsDu/brynet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月14日(星期五) 上午10:04
收件人:&nbsp;"IronsDu/brynet"<brynet@noreply.github.com&gt;;
抄送:&nbsp;"786436671"<786436671@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [IronsDu/brynet] HttpClient无法执行 (#63)





 
好的，谢谢反应。有问题随时提供。

**Comment by IronsDu** [comment]
👏。解决了就好，才看到消息。
