### ISSUE TITLE
请问如何实现文件上传服务

### ISSUE THREAD

**Issue by yueqianzhang** [IronsDu/brynet#64]

**Comment by IronsDu** [comment]
@yueqianzhang 
比如在HTTP报文处理的函数里（比如 [HttpServer.cpp](https://github.com/IronsDu/brynet/blob/master/examples/HttpServer.cpp#L30)），调用[getBody](https://github.com/IronsDu/brynet/blob/master/include/brynet/net/http/HttpParser.hpp#L113)就能得到上传的内容。
你可以先用PostMan或CURL试着上传文件，用HttpServer.cpp来调试，就知道如何拿到上传的文件了。

我明天空了也试试。

**Comment by IronsDu** [comment]
@yueqianzhang 上述方法是OK的，你可以试试。

**Comment by yueqianzhang** [comment]
ok 谢谢
