### ISSUE TITLE
websocket上传文件问题

### ISSUE THREAD

**Issue by yueqianzhang** [IronsDu/brynet#65]
我用websocket上传文件出现了如下问题，请问怎么解决
![image](https://user-images.githubusercontent.com/20694300/90467153-11c05880-e146-11ea-8f1c-4743181500b1.png)
![image](https://user-images.githubusercontent.com/20694300/90467214-374d6200-e146-11ea-9258-b8d1f99e7fef.png)

**Comment by IronsDu** [comment]
https://github.com/IronsDu/brynet/blob/master/examples/HttpServer.cpp#L65。
给 `AddSocketOption::WithMaxRecvBufferSize`  传递一个更大的值试试看呢。

**Comment by yueqianzhang** [comment]
@IronsDu 试过，不可以，
上传的是音频文件，大小在几十~几百KB
设置很大值，还是走break，
然后进去看有个MIN方法，我把MIN中的两个值都调大也不行
好像因为超出了size_t的大小

**Comment by IronsDu** [comment]
@yueqianzhang 麻烦加一个QQ群：540961187 。 加进来详细聊聊吧。

**Comment by IronsDu** [comment]
leftLen 的值是多少。有上传文件的client测试代码么。

**Comment by yueqianzhang** [comment]
可以不做c++啦，感谢老哥..

**Comment by yueqianzhang** [comment]
测试代码是安卓的，就是发送普通的二进制音频，
如果手动构建个小点的二进制，能发送
直接发送整个音频文件，就收不到
定位到的就是上面的截图，bufferSize 那个地方返回false
