### ISSUE TITLE
httpclient等待消息时长问题

### ISSUE THREAD

**Issue by lizengwu** [IronsDu/brynet#66]
httpclient文件中等到消息是下述方式，需要人为触发，
while(true)
{
	std::this_thread::sleep_for(std::chrono::seconds(1));
	if (brynet::base::app_kbhit())
	{
		break;
	}
}
我改成std::this_thread::sleep_for(std::chrono::seconds(1));方式依然不能满足我的要求，因为时长的设定值不好确定，而且设定太大浪费时间，设定太小的话很可能等不到消息，改成同步的话应该可以，但是改的代码太多了，请问有没有自动触发的机制啊？谢谢

**Comment by IronsDu** [comment]
这个只是测试，提供用户输入按键退出测试程序。 这个并不会影响性能。
等待按键没有异步的，只能同步阻塞。

**Comment by lizengwu** [comment]
可以改成sleep吗？改成sleep的话，sleep的时间我测了下是固定的，设定10s肯定是10s，但是不设定sleep或者人为干预（如例子）消息不一定能收到，这种情况怎么改合适啊？

**Comment by lizengwu** [comment]
大佬您好，其实我只是想借助这个httpclient的代码发http消息，现在遇到的问题是，如果不加您示例代码中的while那一段，收不到消息，改成线程sleep时间长度又是个问题，能不能请教下您这个该怎么做合适啊，想了半天也没想到合适的办法，😭



---原始邮件---
发件人: "IronsDu"<notifications@github.com&gt;
发送时间: 2020年8月20日(周四) 晚上6:40
收件人: "IronsDu/brynet"<brynet@noreply.github.com&gt;;
抄送: "lizengwu"<786436671@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [IronsDu/brynet] httpclient等待消息时长问题 (#66)




 
这个只是测试，提供用户输入按键退出测试程序。 这个并不会影响性能。
 等待按键没有异步的，只能同步阻塞。

**Comment by lizengwu** [comment]
想着能发送消息，收到消息以后，退出线程就好了，我现在是把httpclient这个代码做成了一个函数在main调用的



---原始邮件---
发件人: "IronsDu"<notifications@github.com&gt;
发送时间: 2020年8月20日(周四) 晚上6:40
收件人: "IronsDu/brynet"<brynet@noreply.github.com&gt;;
抄送: "lizengwu"<786436671@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [IronsDu/brynet] httpclient等待消息时长问题 (#66)




 
这个只是测试，提供用户输入按键退出测试程序。 这个并不会影响性能。
 等待按键没有异步的，只能同步阻塞。

**Comment by lizengwu** [comment]
修改代码，已解决，谢谢大佬
