### ISSUE TITLE
http如何设置短连接或者keep-alive的超时时长？谢谢

### ISSUE THREAD

**Issue by lizengwu** [IronsDu/brynet#67]

**Comment by lizengwu** [comment]
已解决，request.addHeadValue("Connection", "close");

**Comment by IronsDu** [comment]
brynet的HTTP只有最基础的功能。譬如keep alive或者压缩等功能，都需要自己来做，之所以提供HTTP，是因为可能需要内网C++服务器里提供一些简单的HTTP API服务。（这是没问题的）

但如果你要开发一个重HTTP服务（而且逻辑不需要C++），确实可以用别的语言，比如C#或者Go。

**Comment by IronsDu** [comment]
嗯，类似brpc之类的用C++实现HTTP API辅助一些功能，够用即可。
但确实在功能上还是简陋了些，比如router啊，middleware啊什么的，都没有。（总之不算一个HTTP框架）

**Comment by lizengwu** [comment]
重http功能的话肯定选go了啊，不过brynet也算是“短小精悍”了，可惜一直没来及深入源码，目前只是侧重于用！！希望后面能深入源码，挺有意思的
