### ISSUE TITLE
请问PingPongServer.cpp文件中service->startWorkerThread(atoi(argv[2]));这里开启多线程后，setDataCallback中如果处理共享数据，加锁解锁是不是要自己来完成啊？比如我在多线程的前提下，在setDataCallback中把buffer写到一个vector<string>中。谢谢

### ISSUE THREAD

**Issue by lizengwu** [IronsDu/brynet#68]

**Comment by IronsDu** [comment]
开启了多线程后，那么你的IO就是多线程的。也就是极有可能同时有多个线程在处理各自接管的socket-session的数据。也就是说setDataCallback的回调函数是有多个线程同时执行（当然，回调函数对象本身是独立的）。所以这个函数里需要你自己处理线程安全问题。

**Comment by lizengwu** [comment]
既然各个线程处理各自的session那就不牵涉保序的问题了，也就是说某一时刻某一个线程处理某个链接的底层buffer数据，setDataCallback也可以理解为各线程有各自的，对共享数据来说其实就是多个线程的竞争问题了，这么理解对吧？谢谢

**Comment by IronsDu** [comment]
1. 你前部分说的没问题。 这个消息回调函数(lambda 对象）是每个session一个，不存在多个session共用了一个回调。并且更重要的是：每个session的消息处理回调只会在一个固定线程里执行（不可能多个线程同时处理同一个session）。
2. 但若这个回调函数里操作一些全局状态，那也务必小心，这极可能会导致线程安全问题。--貌似你后半部分也是我说这个意思。

**Comment by lizengwu** [comment]
感谢大佬，我想表达的也是这个意思，代码写完，搞几个client测试下，谢谢
