### ISSUE TITLE
Buffer filling up quickly / how to end connections

### ISSUE THREAD

**Issue by irieger** [IronsDu/brynet#73]
Hey,

this is kind of a follow up to my last request #70 as I went further with my implementation. As I got a stable sample running I integrated the code into another project to have the image transfer inside an application. Currently I have a class managing the image transmission in a thread where other modules of the software deliver an image defined as in the sample https://gist.github.com/irieger/74808b0db67c39e33d37641e210e26bc. The image transmission currently is done in by first creating a connectionBuilder and then sending the data if an image is in the queue:
```c++
    brynet::net::wrapper::ConnectionBuilder connectionBuilder;
    connectionBuilder.configureService(service)
        .configureConnector(connector)
        .configureConnectionOptions({
            brynet::net::AddSocketOption::AddEnterCallback(enterCallback),
            brynet::net::AddSocketOption::WithMaxRecvBufferSize(m_network_buffer_megabytes * 1024 * 1024)
        });

    bool has_data = false;
    while (m_running)
    {
        {
            std::lock_guard<std::mutex> lock(m_queue_mtx);
            has_data = (m_queue.size() > 0);
        }
        if (has_data)
        {
            try
            {
                connectionBuilder.configureConnectOptions({
                        brynet::net::ConnectOption::WithAddr(m_target_ip, m_target_port),
                        brynet::net::ConnectOption::WithTimeout(std::chrono::seconds(1)),
                        brynet::net::ConnectOption::WithFailedCallback(failedCallback),
                        brynet::net::ConnectOption::AddProcessTcpSocketCallback([](brynet::net::TcpSocket& socket) {
                            socket.setNodelay();
                        })
                    })
                    .asyncConnect();
            }
            catch (std::runtime_error& e)
            {
                std::cerr << "[ImageTransmitter]  error:" << e.what() << std::endl;
            }
        }

        std::this_thread::sleep_for(std::chrono::milliseconds(3));
    }
```

This might not be the ideal solution but worked in my first tests. Today I did some longer experiments and realized my memory usage on the receiver side increased steadily until I ran into errors. As I found out the memory was only freed after closing the sender, thus it seems something isn't freed unless the client connection is stopped. Is this correct? When is the receiver freeing the memory? I expected that after returning the size of processed bytes in the DataCallback the memory would be reused.

The other point is, I now have a number of open connections blocking resources besides the memory usage. Can I automatically close after the send is done? I send with code like this to ensure the data is removed from RAM after the sent (this is the enter callback):
```c++
    auto enterCallback = [this](const brynet::net::TcpConnection::Ptr& session)
    {
        session->setDataCallback([session, this](const char* buffer, size_t len)
        {
            return len;  // No answer is currently expected so should be irrelevant.
        });
        // while (m_running)  // uncommented in alternative route (see below)
        {
            // ... code pulling the next image data/size pair from an std::queue
            // ... fills the following variables:
            char* data;
            size_t data_size;

            // sending the actual data
            session->send(data, data_size, [data]()
                {
                    std::free(data);
                });
            // std::this_thread::sleep_for(std::chrono::milliseconds(10));  // sleep in the alternative case to slow queue/lock checking
        }
```
After the free I'd also like to close the session now but there seems to be no close/disconnect whatever method in this class.

Btw. the `brynet::net::ConnectOption::WithTimeout(std::chrono::seconds(1))` only means a timeout in case the connection can't be established, not an overall timeout, right?

### Alternative route

I tried an alternative route creating one or two sender connections waiting for new data in the queue and sending it. Besides a `while(m_running)` around the block pulling data from the queue and sending it nothing is changed but I don't reach the send callback anymore. This is with or without an additional mutex blocking as long as send is executed (mutex.lock() before the send and mutex.unlock() in the send callback after the `free`.

With the std::cout debug output of the size send data (after the call) I see the sender passed the send call, but the send-Callback isn't reached and neither is the debugging output on the server side showing the DataCallback being called.
Any hint on this?

I could take the time to rewrite the example code to fully show the data flow if needed for understanding what I did.

**Comment by IronsDu** [comment]
Hi, this code is error.
https://gist.github.com/irieger/74808b0db67c39e33d37641e210e26bc#file-server-cpp-L44-L71 。
if not receive complete packet , you need return 0. and, you need while loop check whether receive complete packet.
like this:
https://github.com/IronsDu/gayrpc/blob/master/src/gayrpc/protocol/BinaryProtocol.h#L187

**Comment by IronsDu** [comment]
`Btw. the brynet::net::ConnectOption::WithTimeout(std::chrono::seconds(1)) only means a timeout in case the connection can't be established, not an overall timeout, right?`,
Yes, you are right.

**Comment by IronsDu** [comment]
```
 auto enterCallback = [this](const brynet::net::TcpConnection::Ptr& session)
    {
        session->setDataCallback([session, this](const char* buffer, size_t len)
        {
            return len;  // No answer is currently expected so should be irrelevant.
        });
        // while (m_running)  // uncommented in alternative route (see below)
        {
            // ... code pulling the next image data/size pair from an std::queue
            // ... fills the following variables:
            char* data;
            size_t data_size;

            // sending the actual data
            session->send(data, data_size, [data]()
                {
                    std::free(data);
                });
            // std::this_thread::sleep_for(std::chrono::milliseconds(10));  // sleep in the alternative case to slow queue/lock checking
        }
```
If you need memory cache. you can manager std::shared_ptr<std::string>, like this:
```
auto msg = acquireFromCache();
session->send(msg, []()
{
    releaseToCache(msg);
})
```

**Comment by irieger** [comment]
> if not receive complete packet , you need return 0. and, you need while loop check whether receive complete packet.
> like this:
> https://github.com/IronsDu/gayrpc/blob/master/src/gayrpc/protocol/BinaryProtocol.h#L187
Sorry, forgot to fix the gist from this error. My code has the return 0.

> If you need memory cache. you can manager std::shared_ptrstd::string, like this:
What do you mean there? My sender code seems to be fine besides not closing connections when sending was finished which I find nowhere documented how to do. Haven't run into other problems on the sender side yet and data freeing works as I build it.

Problem is the receiving side not freeing memory while the connection is open (besides the problem that after a while I'd expect the number of connections becoming a problem too when not closed, not the receiver memory only.

**Comment by IronsDu** [comment]
If connection's receive buffer grow up to one size, it never decrease, until connection closed.
emmm, I have a idea:
you can define one small receive buffer. and you use other buffer for parse data in `DataCallback`. So, if you receive completed packet, you can free this buffer.

like this:
```
auto cacheBuffer;
session->setDataCallback([](const char* buffer, size_t len)
{
    cachebuffer.add(buffer, len);
    // parse cache buffer
    // cacheBuffer.keep(left size);
    return len;
}
```

**Comment by IronsDu** [comment]
I'm sorry not provide english document`````my english not good enough.

**Comment by IronsDu** [comment]
you can use https://github.com/IronsDu/brynet/blob/master/include/brynet/base/Packet.hpp#L246 for parse packet. like : https://github.com/IronsDu/gayrpc/blob/master/src/gayrpc/protocol/BinaryProtocol.h#L191

**Comment by irieger** [comment]
> If connection's receive buffer grow up to one size, it never decrease, until connection closed.

So how to close the connection than after successful transfer? As described above that is my problem currently.

**Comment by IronsDu** [comment]
> > If connection's receive buffer grow up to one size, it never decrease, until connection closed.
> 
> So how to close the connection than after successful transfer? As described above that is my problem currently.

```
session->send(msg, [session]()
{
    session->postDisConnect(); // or session->postShutdown();
});
```

**Comment by IronsDu** [comment]
I have a try , that for user specify msg cache manager.
https://github.com/IronsDu/brynet/blob/847ce842a6eb5a78afa1b3d82befd94150c1dbd9/include/brynet/net/TcpConnection.hpp#L39-L71
User can inherit `SendMsg `, overwrite `data` and `size`, and can be release msg to his cache.

**Comment by irieger** [comment]
> ```
> session->send(msg, [session]()
> {
>     session->postDisConnect(); // or session->postShutdown();
> });
> ```

Thank you, that worked. From the name I was expecting those functions to be internal hooks called after disconnecting and was searching for the disconnect itself.

**Comment by IronsDu** [comment]
@irieger Good,  You not found this way  is my fault.
If you have any question, welcome you add issue.

**Comment by IronsDu** [comment]
@irieger I add `TcpConnection::postShrinkReceiveBuffer` support We can call it at regular intervals for shrink receive buffer .

**Comment by IronsDu** [comment]
https://github.com/IronsDu/brynet/blob/master/include/brynet/net/TcpConnection.hpp#L261
