### ISSUE TITLE
请教个问题，详见内文

### ISSUE THREAD

**Issue by lizengwu** [IronsDu/brynet#78]
我使用httpclient携带一个参数，发送http请求到后端，处理正常，携带3个参数，发生异常，新加的两个参数格式为“年 月-日  时-分-秒”，打印出来requestStr看结果，符合预期，能够抓到发出的http请求包，和响应包，响应包为400  badRequest，但是我在setHttpCallback设置的打印未生效，但是使用打印出的requestStr码流，使用postman构造后发出，却能正确处理，请教两个问题：
1、我使用了asyncConnect启动发送请求操作，也使用了while循环保证退出，但是抓包看到400响应，但是为什么设置的回调未成功？
2、发出的http请求码流编码有什么特殊处理吗？我根据打印的码流借助postman发出去，却能正确处理？

**Comment by lizengwu** [comment]
换一种方法找到了问题原因，是由于底层编码的问题，服务端要求空格编码符合RFC2396协议规定（空格要编码为%20），但是brynet直接处理成了空格，这个有办法解决吗？一般来说，现在RFC2396的编码格式更为通用

**Comment by IronsDu** [comment]
> 换一种方法找到了问题原因，是由于底层编码的问题，服务端要求空格编码符合RFC2396协议规定（空格要编码为%20），但是brynet直接处理成了空格，这个有办法解决吗？一般来说，现在RFC2396的编码格式更为通用

你是说HttpRequest里处理成了空格么？

**Comment by lizengwu** [comment]
> equest里处理成了空格么

使用brynet组装http请求，“年 月-日 时-分-秒”，“日”和“时”之间的空格，根据打印和抓包的结果来看，就是空格（“ ”），但是我这边服务端，遵循的是RFC2396协议，我也看了代码，也就是空格要转成%20，才认为是空格，我把代码“年 月-日 时-分-秒”中的空格人为的改成%20，再使用brynet组装param，就可以正确发送且服务端能够正确处理。

**Comment by IronsDu** [comment]
@lizengwu 嗯嗯，我没有提供urlencoding，没有在 https://github.com/IronsDu/brynet/blob/master/include/brynet/net/http/HttpFormat.hpp#L115 自动转换，需要用户自己转换。

**Comment by lizengwu** [comment]
> @lizengwu 嗯嗯，我没有提供urlencoding，没有在 https://github.com/IronsDu/brynet/blob/master/include/brynet/net/http/HttpFormat.hpp#L115 自动转换，需要用户自己转换。

好的，感谢大佬！

**Comment by IronsDu** [comment]
@lizengwu 因为只提供最基础的API，所以不像Java\C#\Go那么丰富。
如果你只是在长连接服务里提供少量的API，那么可以用。
但如果你写非常重度（多）的HTTP API，我觉得可以用其他语言更好点。

**Comment by lizengwu** [comment]
> @lizengwu 因为只提供最基础的API，所以不像Java\C#\Go那么丰富。
> 如果你只是在长连接服务里提供少量的API，那么可以用。
> 但如果你写非常重度（多）的HTTP API，我觉得可以用其他语言更好点。

一直在用，用的都是基本功能，感谢解答
