### ISSUE TITLE
请问，maxRecvBufferSize设置大小的原则是什么？太大的话，会不会引起系统coredump？以HTTPClient为例，如果需要接收的响应body比较大，比如100M，我的RecvBufferSize是不是不能小于该值？谢谢

### ISSUE THREAD

**Issue by lizengwu** [IronsDu/brynet#79]

**Comment by IronsDu** [comment]
1. 对于HTTP的话（因为HTTP的解析不依赖它，因为HTTP 解析总是把底层收到的数据全部处理了，注意与第3点的差别)，所以不需要设置100M。哪怕设置为1byte也行。
2. 这个maxRecvBufferSize是设置一个最大读缓冲区大小（但底层不会一开始就创建那么大，有可能压力一直很小，一直不会增长到最大值）
3. 此值通常用于用户只解析完整包的情况下，也即：非完整包的数据会遗留在底层的recvBuffer里，因此这种情况下必须要求：maxRecvBufferSize >= 逻辑上的最大包长度。
4. 此值也为了提升效率：因为缓冲区越大，单次recv能接受的数据就越多，这可能减小系统调用次数。（当然需要要权衡，太大了可能浪费内存，不过我们可以定期调用postShrinkReceiveBuffer来尝试紧缩内存--即当然recv buffer有可能分配到很大，但其实实际使用的并不大）

**Comment by lizengwu** [comment]
是不是可以这么理解，maxRecvBufferSize只是用户读缓冲，即从socket缓冲区接收数据时使用，所以它的大小影响性能主要是影响调用的次数，因为要组包，对于您说的第三条，“此值通常用于用户只解析完整包的情况下，也即：非完整包的数据会遗留在底层的recvBuffer里，因此这种情况下必须要求：maxRecvBufferSize >= 逻辑上的最大包长度”，什么情况下能发生呢？连着2个请求吗？

**Comment by lizengwu** [comment]
测试HTTP client代码时候，我设置了maxRecvBufferSize为10240000，连续跑了5个小时后发生了“terminate called after throwing an instance of 'std::bad_alloc'  what():  std::bad_alloc”错误，WithFailedCallback中我设置了log打印，的确也打印了，也就是说这次的请求失败了，所以我怀疑是不是和设置maxRecvBufferSize太大有关系

**Comment by IronsDu** [comment]
@lizengwu 加我QQ: 790390398
