### ISSUE TITLE
Feauture Request: Add REUSEPORT and REUSEADDR

### ISSUE THREAD

**Issue by ibroheem** [IronsDu/brynet#81]
This feature allows us to run multiple instance of the same App running on a single port.
I have this I'm using in my code in `/brynet/net/SocketLibFunction.hpp`

```
  static int  SocketSetReusePort(BrynetSocketFD fd)
  {
     int enable = 1;
     return ::setsockopt(fd, SOL_SOCKET, SO_REUSEADDR | SO_REUSEPORT, &enable, sizeof(enable));
  }
```
The issue now is where to put it. I currently call this function in `brynet/net/SocketLibFunction.hpp` in ``
```
        const auto socketfd = isIPV6 ?
            socket(AF_INET6, SOCK_STREAM, 0) :
            socket(AF_INET, SOCK_STREAM, 0);
        if (socketfd == BRYNET_INVALID_SOCKET)
        {
            return BRYNET_INVALID_SOCKET;
        }

        SocketSetReusePort(socketfd);
...
```

I tried adding:
```
        void             setReusePort(bool yes = true)
        {
            if (yes)
            {
               brynet::net::base::SocketSetReusePort(mFD);
            }
        }
```
to `Socket.hpp,` it seems nothing in 
```
.configureSocketOptions({
                [&](TcpSocket& socket) {
                    socket.setReuseAddr(true);
                    socket.setReusePort(true);
                    socket.setNodelay();
            },
        })
```
ever gets called.

**Comment by IronsDu** [comment]
Hi, Are you say this function not be called？

**Comment by IronsDu** [comment]
https://github.com/IronsDu/brynet/blob/master/include/brynet/net/SocketLibFunction.hpp#L193 about listen socket, already reuse addr.

**Comment by ibroheem** [comment]
Yes, but there's no SO_REUSEPORT.
1. Let us add  SO_REUSEPORT
2. Probably make them optional via setReusePort() and setReuseAddr()

**Comment by IronsDu** [comment]
Hi, @ibroheem 
I support enable reuse_port in this PR #82.
We have two to enable reuse_port.

1. call `BuildListenConfig::enableReusePort` in `listenBuilder::configureListen`
2. call `ListenThread::Create`, pass `true` for `bool enabledReusePort` argument..

But, we add a question: If enable SO_REUSEPORT, we may can't wakeup listen when want close server.

**Comment by IronsDu** [comment]
After you think this PR is OK, please tell me, i will merge it.

**Comment by ibroheem** [comment]
I tested the PR and I can confirm it's OK. I used:

```
listenBuilder.configureListen([port](wrapper::BuildListenConfig builder) {
    builder.enableReusePort();
    builder.setAddr(false, "0.0.0.0", port);
});
```

**Comment by IronsDu** [comment]
Thanks. It's done.

**Comment by IronsDu** [comment]
@ibroheem If not have probelem, can you close this issue?
