### ISSUE TITLE
问个小白问题：无法解析的外部符号 __imp_closesocket

### ISSUE THREAD

**Issue by ActivePeter** [IronsDu/brynet#86]
编译遇到这个咋整

**Comment by IronsDu** [comment]
需要在VS的链接器设置里设置链接 ws2_32.lib 。

**Comment by ActivePeter** [comment]
> 需要在VS的链接器设置里设置链接 ws2_32.lib 。

哦哦解决了，我是在cmakelist里加的 target_link_libraries (${PROJECT_NAME} ws2_32)

**Comment by ActivePeter** [comment]
> 需要在VS的链接器设置里设置链接 ws2_32.lib 。

哦哦解决了，我是在cmakelist里加的 target_link_libraries (${PROJECT_NAME} ws2_32)

**Comment by IronsDu** [comment]
暂时先关闭此issue。若有问题再请再提吧。
