### ISSUE TITLE
请问解析ws消息时有考虑粘包和分包问题吗?

### ISSUE THREAD

**Issue by tonyonce2017** [IronsDu/brynet#94]
如题

**Comment by IronsDu** [comment]
ws本就是应用层协议，解析出了ws就自然不会考虑所谓的TCP流协议带来的一些"问题"。

**Comment by tonyonce2017** [comment]
> ws本就是应用层协议，解析出了ws就自然不会考虑所谓的TCP流协议带来的一些"问题"。

我自己封装ws协议的时候, 需要考虑它的分包和粘包, 不然解析出来的ws会有问题

**Comment by IronsDu** [comment]
你说ws里的非完整包么？

**Comment by IronsDu** [comment]
https://github.com/IronsDu/brynet/blob/1b4a9623b5d6502bd912dd8b106fb3462d7f6ab4/include/brynet/net/http/HttpService.hpp#L238

**Comment by tonyonce2017** [comment]
> 你说ws里的非完整包么？

你有遇到过一个tcp buff里有2条ws消息的情况吗

**Comment by IronsDu** [comment]
> > 你说ws里的非完整包么？
> 
> 你有遇到过一个tcp buff里有2条ws消息的情况吗

这肯定会遇到。

**Comment by dourgulf** [comment]
TCP是流式协议，没有”包“的概念，TCP之上的协议才有协议包。所谓分包的逻辑就肯定是上层协议处理，而非这个库处理的。

**Comment by IronsDu** [comment]
> TCP是流式协议，没有”包“的概念，TCP之上的协议才有协议包。所谓分包的逻辑就肯定是上层协议处理，而非这个库处理的。

嗯，不过brynet支持websocket，所以用户不必关心TCP流协议问题。
